### ISSUE TITLE
ambient wrong value

### ISSUE THREAD

**Issue by MSJocke** [thehookup/RGBW-Sunrise-Animation-Neopixel-#3]
Hi,

noticed that the drawambient sets the wrong value (is this by design or a bug?)

my suggestion: 
void drawAmbient()
{

  for(int i = 0; i < NUM_LEDS; i++)
  {
    strip.setPixelColor(i,0,0,0,whiteLevel); // ### corrected 
  }

}

**Comment by thehookup** [comment]
This issue was opened a long time ago! Thanks for letting me know github... lol.

It was indeed a feature not a bug, I wanted to set the color of the red channel, but I was already modifying the "whiteLevel" variable, so I decided to just use the whiteLevel to change redLevel.
