### ISSUE TITLE
Random Reset issue?  

### ISSUE THREAD

**Issue by thedannymullen** [thehookup/RGBW-Sunrise-Animation-Neopixel-#5]
I added the wifi and mqtt settings then, I loaded the code into a nodemcu.  

I would love a compiled binary, but the mqtt and wifi gets in the way of that.   So I suppose its question time?  Should I post the versions of libraries and arduino IDE?  Maybe compare to yours?  

I had a problem with EsPpixel stick once.  If I compiled with the latest of one library it had an issue.  Figured it out when I switch to my mac I don't use often, with the older library set.

08:25:04.622 -> Connecting to Iot_Net
08:25:05.138 -> ..
08:25:05.623 -> WiFi connected
08:25:05.623 -> IP address: 
08:25:05.623 -> 192.168.1.211
08:25:05.623 -> Attempting MQTT connection...connected
08:50:04.293 -> 
08:50:04.293 ->  ets Jan  8 2013,rst cause:4, boot mode:(3,6)
08:50:04.327 -> 
08:50:04.327 -> wdt reset
08:50:04.327 -> load 0x4010f000, len 1392, room 16 
08:50:04.327 -> tail 0
08:50:04.327 -> chksum 0xd0
08:50:04.327 -> csum 0xd0
08:50:04.327 -> v3d128e5c
08:50:04.327 -> ~ld
08:50:04.394 -> 
08:50:04.394 -> Connecting to Iot_Net
08:50:04.879 -> ..
08:50:05.395 -> WiFi connected
08:50:05.395 -> IP address: 
08:50:05.395 -> 192.168.1.211
08:50:05.395 -> Attempting MQTT connection...connected

I believe it may pertain to the timer used, but I am not able to pin point it yet.  Was curious if you or others have seen this?  I put prints in to see if I could find the last sub that may have caused a reset, but have had no luck.  I also turned on Arduino debug, that was just gibberish... in assembly code.  I forgot my assembly 30yrs ago LOL...  

I say it pertains to timers as when I change the number of LEDs the resets happen faster.  Below is with LED of 30 as that is what I have on my test strip of 1m.  

08:57:55.391 -> Connecting to Iot_Net
08:57:55.998 -> ........
08:58:00.300 -> WiFi connected
08:58:00.300 -> IP address: 
08:58:00.300 -> 192.168.1.211
08:58:00.300 -> Attempting MQTT connection...connected
08:59:26.999 -> 
08:59:26.999 ->  ets Jan  8 2013,rst cause:4, boot mode:(3,6)
08:59:26.999 -> 
08:59:26.999 -> wdt reset
08:59:26.999 -> load 0x4010f000, len 1392, room 16 
08:59:26.999 -> tail 0
08:59:26.999 -> chksum 0xd0
08:59:26.999 -> csum 0xd0
08:59:26.999 -> v3d128e5c
08:59:26.999 -> ~ld
08:59:27.066 -> 
08:59:27.066 -> Connecting to Iot_Net
08:59:27.652 -> ........
08:59:31.950 -> WiFi connected
08:59:31.950 -> IP address: 
08:59:31.950 -> 192.168.1.211
08:59:31.950 -> Attempting MQTT connection...connected

**Comment by bbacskay** [comment]
According the logs you have a hardware watchdog reset problem. That means the program spends too much time somewhere and doesn't reset the watchdog timer in time.
I traced this problem back to the Adafruit_Neopixel library. It was OK with a short strip, but with 150 it reseted in every couple hours.
Try to upgrade the Adafruit_Neopixel library to the latest version and recompile the code with it.

Good reading on the ESP8266 watchdog:
[https://www.sigmdel.ca/michel/program/esp8266/arduino/watchdogs_en.html](https://www.sigmdel.ca/michel/program/esp8266/arduino/watchdogs_en.html)

**Comment by thedannymullen** [comment]
Will go check it out!!  Thanks!

**Comment by thedannymullen** [comment]
Ok downloaded the 1.35 release of Adafruit_NeoPixel.  Still have the issue, I confirmed it is using the new one by renaming the file and having the compile fail.

**Comment by bbacskay** [comment]
A couple of months ago I made my own fork of this repo. I replaced the Adafruit_Neopixel library with the NeoPixelBus library. And I made the program compatible with the ESP32 as well. My Sunrise strip still runs on a NodeMCU though.
If you are interested in it check out the 'develop' branch from it.

**Comment by thedannymullen** [comment]
@bbacskay thanks so much for info.  I installed the new library, but I can't find your development branch.  Github says page not found.

**Comment by bbacskay** [comment]
This is the repo:
[https://github.com/bbacskay/RGBW-Sunrise-Animation-Neopixel-](https://github.com/bbacskay/RGBW-Sunrise-Animation-Neopixel-)
First you have to clone the repo to your computer:
`git clone https://github.com/bbacskay/RGBW-Sunrise-Animation-Neopixel-.git`
Then switch to the develop branch:
`git checkout develop`

Or

You can download the sources of the develop branch as a zip file. There is dropdown selection for the branches, select the develop there, then click the Clone or download button and then the Download ZIP.

**Comment by thedannymullen** [comment]
@bbacskay I have it downloaded and compiled now.    Running for over an hour with no reset.  I am confident this should work!  Thanks for all the help!!!

**Comment by charredchar** [comment]
@bbacskay Sorry to ping you here but I have been running into this same exact issue and I am attempting to run your developer build. So far I haven't seen any reset but I have one big problem, it won't turn on any of the LEDs! I have two NodeMCUs and it does the same on both, the original code works great except for the same rebooting and LEDs flashing. I sadly do not know enough about coding an MCU yet to know where I should be looking for turning on the LEDs. I plugged one in via USB to use the serial monitor as well as watching the MQTT on Home Assistant and both show that everything appears normal, receiving commands and everything.

**Comment by bbacskay** [comment]
@charredchar To which pin did you connect the data pin of the LED strip and what did you set as LED_PIN value (within the #else branch) in your config.h?
Most likely the data is sent to an incorrect pin. Other option, that something has changed in the NeoPixelBus library. When I last compiled this project I used the 2.5.7 version. Now the latest is 2.6.0.

**Comment by charredchar** [comment]
I left it as the default pin 5, which is D1 on the NodeMCU. I did attempt changing it to pin 4 during troubleshooting and changed it in the config.h, which is D2 on the NodeMCU. Neither worked.

Thank for letting me know which version you used! This has been my biggest announce with these projects, people don't list which library version they used and something ends up not working. Sadly, this didn't work either...

I did just notice (didn't before as the NodeMCU is in another room from my desktop) that the WiFi LED does turn on when ever I attempt to turn on the LED strip. Seeing this, out of a bit of frustration I just started plugging the LED data pin into any of the NodeMCU pins that wouldn't harm it... It works on GPIO3! (Labled RX on the NodeMCU) I am happy it works but knowing why there is a dependency would be nice, my assumption is something in a library.

**Comment by bbacskay** [comment]
You are right, it is a limitation of the NeoPixelBus library on the ESP8266. Here is the info: [https://github.com/Makuna/NeoPixelBus/wiki/FAQ-%231](https://github.com/Makuna/NeoPixelBus/wiki/FAQ-%231)

**Comment by charredchar** [comment]
> You are right, it is a limitation of the NeoPixelBus library on the ESP8266. Here is the info: https://github.com/Makuna/NeoPixelBus/wiki/FAQ-%231

Thank you a ton for that link, it does clear some things up and helps in knowing you can only use GPIO 2 or 3 on the ESP8266. I still find it weird that setting pin 5 in the config goes to 3 but my guess there is anything higher than 3 just goes to 3...

**Comment by freddieleeman** [comment]
Switching to GPIO3 (TX) on my ESP8266 fixed my issues too. Thanks for the information!
